# coder-provisioner-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workspace-provisioner-role
  namespace: coder-workspaces
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-provisioning-binding
  namespace: coder-workspaces
subjects:
- kind: ServiceAccount
  name: coder
  namespace: coder
roleRef:
  kind: Role
  name: workspace-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-provisioning-binding
  namespace: coder-workspaces
subjects:
- kind: ServiceAccount
  name: arc-runner-coder-provisioner
  namespace: arc-runners
roleRef:
  kind: Role
  name: workspace-provisioner-role
  apiGroup: rbac.authorization.k8s.io
