coder:
    # You can specify any environment variables you'd like to pass to Coder
    # here. Coder consumes environment variables listed in
    # `coder server --help`, and these environment variables are also passed
    # to the workspace provisioner (so you can consume them in your Terraform
    # templates for auth keys etc.).
    #
    # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
    # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
    # they are already set by the Helm chart and will cause conflicts.
    env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
                # You'll need to create a secret called coder-db-url with your
                # Postgres connection URL like:
                # postgres://coder:password@postgres:5432/coder?sslmode=disable
                name: coder-db-url
                key: ENC[AES256_GCM,data:9LT8,iv:wrbaVrD5Nv5L+vQtEdeViCT+4OsooNwV67DRQ3uWbhc=,tag:f8KDisFqPPP1WKTcjmUbxA==,type:str]
        # For production deployments, we recommend configuring your own GitHub
        # OAuth2 provider and disabling the default one.
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: ENC[AES256_GCM,data:Ly1AtxY=,iv:JZKYVWJAUrKDiak2Y5Uw3Xyj5dAgo84E2Ptc7D41eqI=,tag:FdXnzIrkKrHuW7JMLgULWg==,type:str]
        # External identity for Coder
        - name: CODER_ACCESS_URL
          value: ENC[AES256_GCM,data:Ju6t1VxNDYtQEeDMtiwOwjBqW38IiTPrM/kt+S6K+8R1Dzo=,iv:JTUB2Zj0dd/Emb31ShpWEInNGH/2sOOxzeR3XBKcnWg=,tag:Bab0dcpLVrGdl4j29UipLw==,type:str]
        # Trust Cloudflare Proxy headers
        - name: CODER_PROXY_TRUSTED_PROXIES
          value: ENC[AES256_GCM,data:4rA/Yn6jN5fQqipPTpqUFFELwSlFVqfh/i7X/vnlagJMSB/9U6LF,iv:OdlheVrbivjbO+pdW2shNhllbfBO88TuY7afUWtS8ZM=,tag:YTYAZbU51WFuYZ2TvKTnbg==,type:str]
        # GitHub OAuth
        - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
          value: ENC[AES256_GCM,data:9XbmYg==,iv:QLpLYChzyTaLCwbs5WxhRyu5rWiTVIlPwbklImeNK6k=,tag:1S8ESQWVyvcDRrV58JfTOg==,type:str]
        - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
          value: ENC[AES256_GCM,data:jprqLB1C4UmgKz+lhVLsVq8=,iv:NN2e0otXUcXCp/15njBKkYr99lSwLloYEo7CpjkKEOQ=,tag:I9+gtteQSphuDi1zQIbHWw==,type:str]
        - name: CODER_OAUTH2_GITHUB_CLIENT_ID
          value: ENC[AES256_GCM,data:UK6RRORUWWoOEUXZ33oaYFJd0fk=,iv:RtVfoj/hrUl5nNMmSqxtD/+HWbOGeONSY+sRQ7jbaTQ=,tag:ZXSpGzdPMSnaUYgsoQBAPw==,type:str]
        - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
          value: ENC[AES256_GCM,data:GL7guj6vLOc//8FDDR0/wXiGIVzwbH8FBnz804BZnl21RdP0lSRqcw==,iv:86CH98hQ55j3C4J2GXiTRvWlwi1xaDzVLI/KArKxgbE=,tag:rbloJbjjOc8NvSlplf8NPw==,type:str]
        - name: CODER_SECURE_AUTH_COOKIE
          value: ENC[AES256_GCM,data:9XbmYg==,iv:QLpLYChzyTaLCwbs5WxhRyu5rWiTVIlPwbklImeNK6k=,tag:1S8ESQWVyvcDRrV58JfTOg==,type:str]
        # GitHub External Auth
        - name: CODER_EXTERNAL_AUTH_0_ID
          value: ENC[AES256_GCM,data:vvluUzJxrdEvAsxjv4Q=,iv:PdCWBzXDi6wttn6QamdaJZppMaTLVfHpHBRUIoWpu7M=,tag:5TB2P/ysiKcJZCtSF326pg==,type:str]
        - name: CODER_EXTERNAL_AUTH_0_TYPE
          value: ENC[AES256_GCM,data:YUZIITd1,iv:iJI7DUQRlXHhp/Xhd00uCXbYnpiq447fGXkpJPR1Uy4=,tag:WJ0HHItKY/eohCC5zgyzQQ==,type:str]
        - name: CODER_EXTERNAL_AUTH_0_CLIENT_ID
          value: ENC[AES256_GCM,data:UK6RRORUWWoOEUXZ33oaYFJd0fk=,iv:RtVfoj/hrUl5nNMmSqxtD/+HWbOGeONSY+sRQ7jbaTQ=,tag:ZXSpGzdPMSnaUYgsoQBAPw==,type:str]
        - name: CODER_EXTERNAL_AUTH_0_CLIENT_SECRET
          value: ENC[AES256_GCM,data:GL7guj6vLOc//8FDDR0/wXiGIVzwbH8FBnz804BZnl21RdP0lSRqcw==,iv:86CH98hQ55j3C4J2GXiTRvWlwi1xaDzVLI/KArKxgbE=,tag:rbloJbjjOc8NvSlplf8NPw==,type:str]
        - name: CODER_EXTERNAL_AUTH_0_REGEX
          value: ENC[AES256_GCM,data:q4vRFirXu0YiH8XDcTnX,iv:LujZ3RFGt99Hi9n/SQstUOXjGMSCOu77uIcp/5dZ5X0=,tag:L6+bas52MGW+4iX3yyDTfQ==,type:str]
        - name: CODER_EXTERNAL_AUTH_0_SCOPES
          value: ENC[AES256_GCM,data:PVfuhDNqBabuJU2Ik0EtaziKDYxNKp4omA==,iv:ko0Xc6qG2A0Y/aAmxRCSbC3pUYsYkJ+d5yIf/nIod4Y=,tag:uEJ2t5TomMXZ1tc+tgIzlA==,type:str]
#tls:
#  secretNames:
#    - my-tls-secret-name
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:840414111995:key/479cf093-8169-457d-bec2-adc3db73bd85
          created_at: "2026-02-27T19:10:57Z"
          enc: AQICAHhKu0QF7A66OFIKdNNHjoidBZ1H5yC9ninoNeaKENXWtAFP1R/nMbs5PNk5ME/dObpaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMxVt3TYUWlnFlM4kIAgEQgDuOo0l5T/c38vTuIT/tnwGKRpPOI2A/OBLWneZziS7Wagrfy7Rauj5uAaip5U9Co6exXTJ9RMrFWQ3KLw==
          aws_profile: ""
    lastmodified: "2026-02-27T22:49:07Z"
    mac: ENC[AES256_GCM,data:QpHm+C6wqHSvyrGd1lIizeIVJCmTt8TrGulHxdAkS7uDiQK8T9RR2KNFl1QDBULj+WABt+ofLk7rVLyfqXJFHqt8p7IwrWIr6u+pTxQOhWaYwKBDAa1b7cEqt4W90uLGyWH/CitDG2gPHX4XpDwE7keRFwc8XTd2xnw0kqwMuu0=,iv:c+IckqU0g+vFoC7flbwljhV1BeNKxly65HxrP5rU48I=,tag:w3AFndO5F5g2WtqX7PePmw==,type:str]
    encrypted_regex: ^(value|token|crt|key|secret)$
    version: 3.11.0
